
services:
  database:
    image: postgres:15
    container_name: licenta_postgres
    environment:
      POSTGRES_USER: licenta_user
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: licenta_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: